###
## for local dev, wait for db to pass healthcheck before we start node
## also, build custom dockerfile to the dev stage
###

services:
  node:
    build:
      # build to the stage named dev
      target: dev
    ports:
      - '5173:5173'
    environment:
      # Ideally, it should be stored as a secret, but looks like Prisma
      # basically requires this env var to exist
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb?schema=public
      JWT_ACCESS_FILE: /run/secrets/jwt-access
    secrets:
      - jwt-access
    depends_on:
      prisma-migrate-deploy:
        condition: service_completed_successfully
    profiles:
      - dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json

  prisma-migrate-deploy:
    build:
      target: dev
    command: ['npx', 'prisma', 'migrate', 'deploy']
    environment:
      # Ideally, it should be stored as a secret, but looks like Prisma
      # basically requires this env var to exist
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb?schema=public
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./prisma/migrations
          target: /app/prisma/migrations

  prisma-db-seed:
    build:
      target: dev
    command: ['npx', 'prisma', 'db', 'seed']
    environment:
      # Ideally, it should be stored as a secret, but looks like Prisma
      # basically requires this env var to exist
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb?schema=public
    depends_on:
      prisma-migrate-deploy:
        condition: service_completed_successfully
    profiles:
      - seed

  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      # It should be a secret but I was unable to make it work
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: '5s'

secrets:
  jwt-access:
    file: jwt-access-secret

volumes:
  db-data:
